version: '3'
services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - '.:/app'
      - "/app/node_modules"
